/** Auto-generated by scripts/generate-product-cards.mjs — do not edit by hand */
import type { ProductCardSummary } from "@/types";

export const PRODUCT_CARDS: ProductCardSummary[] = [
  {
    "id": "prod-shiatsu",
    "slug": "shiatsu-neck-shoulder-massager",
    "nameAr": "جهاز تدليك الرقبة والكتفين شياتسو 3D مع تدفئة (محاكاة اليد)",
    "price": 399,
    "hero": "/products/shiatsu-neck-shoulder-massager/02-premium-hero.webp"
  },
  {
    "id": "prod-mx003",
    "slug": "astronaut-bt-speaker-projector",
    "nameAr": "بروجيكتور رائد الفضاء بلوتوث MX003",
    "price": 189,
    "hero": "/products/astronaut-bt-speaker-projector/02-premium-hero.webp"
  },
  {
    "id": "prod-starbt",
    "slug": "bluetooth-star-projector",
    "nameAr": "بروجيكتور المجرة والنجوم متعدد الألوان بسبيكر وريموت",
    "price": 169,
    "hero": "/products/bluetooth-star-projector/02-premium-hero.webp"
  },
  {
    "id": "prod-aurora",
    "slug": "northern-lights-galaxy-projector",
    "nameAr": "بروجيكتور الأورورا الهندسي — غرفتك تصير مجرة",
    "price": 249,
    "hero": "/products/northern-lights-galaxy-projector/02-premium-hero.webp"
  },
  {
    "id": "prod-rabbit",
    "slug": "rabbit-carousel-night-light",
    "nameAr": "كاروسيل الأرانب الوردي — 6 أفلام إسقاط ودوران 360°",
    "price": 249,
    "hero": "/products/rabbit-carousel-night-light/02-premium-hero.webp"
  },
  {
    "id": "prod-laser303",
    "slug": "green-laser-pointer-303",
    "nameAr": "ليزر أخضر 303 احترافي — قوي وقابل للشحن ومدى بعيد",
    "price": 199,
    "hero": "/products/green-laser-pointer-303/02-premium-hero.webp"
  },
  {
    "id": "prod-galaxy-rgb",
    "slug": "star-galaxy-projector-rgb-gift",
    "nameAr": "مصباح عرض النجوم والمجرة مع شريط إضاءة RGB هدية",
    "price": 199,
    "hero": "/products/star-galaxy-projector-rgb-gift/02-premium-hero.webp"
  },
  {
    "id": "prod-car-mount",
    "slug": "magnetic-car-phone-mount-maidsail",
    "nameAr": "حامل هاتف مغناطيسي للسيارة Maidsail — MagSafe وذراع قابل للتعديل",
    "price": 159,
    "hero": "/products/magnetic-car-phone-mount-maidsail/02-premium-hero.webp"
  },
  {
    "id": "prod-car-mount-199",
    "slug": "magnetic-car-phone-mount",
    "nameAr": "حامل هاتف مغناطيسي للسيارة — MagSafe وذراع قابل للتعديل",
    "price": 199,
    "hero": "/products/magnetic-car-phone-mount/02-premium-hero.webp"
  },
  {
    "id": "prod-car-mount-1plus1",
    "slug": "magnetic-car-phone-holder-1-plus-1",
    "nameAr": "حامل الهاتف المغناطيسي للسيارة — 1 + 1 مجاناً",
    "price": 199,
    "hero": "/products/magnetic-car-phone-holder-1-plus-1/02-premium-hero.webp"
  },
  {
    "id": "prod-car-fan-sunshade",
    "slug": "car-dual-fan-foldable-sunshade-2in1-pack",
    "nameAr": "باك 2 في 1: مروحة سيارة مزدوجة مع مظلة شمس أمامية قابلة للطي",
    "price": 249,
    "hero": "/products/car-dual-fan-foldable-sunshade-2in1-pack/02-premium-hero.webp"
  },
  {
    "id": "prod-mosquito-tent",
    "slug": "foldable-mosquito-bed-tent",
    "nameAr": "خيمة الحماية من الناموس بتصميم قابل للطي وسريع التركيب",
    "price": 199,
    "hero": "/products/foldable-mosquito-bed-tent/02-premium-hero.webp"
  },
  {
    "id": "prod-dual-cooler",
    "slug": "portable-rechargeable-dual-fan-air-cooler",
    "nameAr": "مبرد هواء محمول قابل للشحن مع مروحتين وتدفق هواء قوي وتصميم مكتبي أنيق",
    "price": 249,
    "hero": "/products/portable-rechargeable-dual-fan-air-cooler/02-premium-hero.webp"
  },
  {
    "id": "prod-vintage-lantern",
    "slug": "vintage-led-lantern",
    "nameAr": "فانوس LED كلاسيكي للديكور والإضاءة الدافئة",
    "price": 229,
    "hero": "/products/vintage-led-lantern/02-premium-hero.webp"
  },
  {
    "id": "prod-warm-led-lamp",
    "slug": "warm-led-decor-lamp",
    "nameAr": "مصباح LED ديكوري بإضاءة دافئة",
    "price": 199,
    "hero": "/products/warm-led-decor-lamp/02-premium-hero.webp"
  },
  {
    "id": "prod-calc-tablet",
    "slug": "solar-calculator-lcd-notepad",
    "nameAr": "آلة حاسبة إلكترونية مع لوح كتابة",
    "price": 249,
    "hero": "/products/solar-calculator-lcd-notepad/02-premium-hero.webp"
  },
  {
    "id": "prod-heli-freshener",
    "slug": "solar-helicopter-car-air-freshener",
    "nameAr": "معطر سيارة شمسي بشكل هليكوبتر — راحة وديكور",
    "price": 169,
    "hero": "/products/solar-helicopter-car-air-freshener/02-premium-hero.webp"
  },
  {
    "id": "prod-sunshade",
    "slug": "foldable-car-windshield-sunshade",
    "nameAr": "مظلة شمس أمامية للسيارة قابلة للطي — حماية من الحر والأشعة",
    "price": 149,
    "hero": "/products/foldable-car-windshield-sunshade/02-premium-hero.webp"
  },
  {
    "id": "prod-mini-vacuum",
    "slug": "cordless-mini-vacuum-keyboard",
    "nameAr": "مكنسة لاسلكية صغيرة 2 في 1 لتنظيف الكيبورد",
    "price": 149,
    "hero": "/products/cordless-mini-vacuum-keyboard/02-premium-hero.webp"
  },
  {
    "id": "prod-kids-art-208",
    "slug": "kids-art-set-easel-208",
    "nameAr": "طقم رسم للأطفال 208 قطعة مع حامل مدمج",
    "price": 299,
    "hero": "/products/kids-art-set-easel-208/02-premium-hero.webp"
  },
  {
    "id": "prod-mini-egg-boiler",
    "slug": "mini-egg-boiler",
    "nameAr": "جهاز كهربائي لطهي البيض",
    "price": 199,
    "hero": "/products/mini-egg-boiler/02-premium-hero.webp"
  },
  {
    "id": "prod-curves-glow",
    "slug": "proteine-curve-collagen-glow",
    "nameAr": "Pack Curves & Glow — بروتين الشكل الأنثوي + كولاجين بحري هدية",
    "price": 399,
    "hero": "/products/proteine-curve-collagen-glow/02-premium-hero.webp"
  },
  {
    "id": "prod-bt12",
    "slug": "bt12-4in1-selfie-stick-tripod",
    "nameAr": "عصا سيلفي BT12 4 في 1 مع ترايبود وضوئين دائريين",
    "price": 349,
    "hero": "/products/bt12-4in1-selfie-stick-tripod/02-premium-hero.webp"
  }
];

export function getProductCardById(id: string): ProductCardSummary | undefined {
  return PRODUCT_CARDS.find((p) => p.id === id);
}

export function getProductCardsByIds(ids: string[]): ProductCardSummary[] {
  const out: ProductCardSummary[] = [];
  for (const id of ids) {
    const card = getProductCardById(id);
    if (card) out.push(card);
  }
  return out;
}

export function getFallbackRelatedCards(excludeId: string, limit = 4): ProductCardSummary[] {
  return PRODUCT_CARDS.filter((p) => p.id !== excludeId).slice(0, limit);
}
